-- The Veil: Combat Recorder (Pantheon toggle for "[Dev] Veil Combat Recorder.lua").
-- GENERATED by tools/sync_recorder.py -- edit the standalone file, then re-run it.
--
-- Passive: watches mob attacks, your hits taken, your dashes/weaves, and writes
-- workspace/Veil_Combat/{summary,timeline,events}_<time>.* -- the same files the
-- standalone script writes, so boss_watch.py / miss_report.py read them unchanged.
-- Keys while on: End = stop, Insert = MARK line, Delete = flush now.

local feature = require("ui.feature")
local log     = require("core.log")

local ID = "veil.combat_recorder"
local Recorder = {}
local stopping = false

local function G() return getgenv and getgenv() or _G end

local function launch()
-- ======================================================= standalone body
    -- [Dev] Veil Combat Recorder -- passive logger for building an auto dodge / weave.
    --
    -- Run it and just play. It touches nothing, it only watches and writes to file:
    --
    --   ENEMY SIDE (mobs in workspace.Monsters, summons skipped)
    --     * every attack animation a mob starts near you: id, name, length, priority, distance,
    --       whether it was facing you, how fast it was closing in, its attributes at that moment
    --     * named keyframes those animations hit (a free "swing now" marker if the game has them)
    --     * attributes / state objects that appear on the mob mid-attack (Attacking flags etc.)
    --     * sounds the mob plays, timed from the start of its attack
    --     * hitbox-looking parts and projectiles spawning near you: size, speed, whether a
    --       projectile is on course for you, its ETA and how close it would pass
    --     * every time you lose health: which attack most likely did it and HOW LONG after that
    --       attack's animation started (= the dodge window you have to beat)
    --
    --   YOUR SIDE (so the script knows what a dash / weave looks like)
    --     * keys you press, your own animations, remotes you fire (FireServer / InvokeServer)
    --     * things added to / removed from your character with their lifetime (i-frame markers),
    --       attribute + value changes (stamina, weave stacks, stuns), WalkSpeed / state changes
    --     * HUD text that mentions weave / dodge / stacks / stamina
    --     * server -> client remote traffic (the server may announce attacks)
    --
    -- FILES (Wave workspace/Veil_Combat/, one set per run):
    --   summary_<time>.txt    the tables: attack timings per mob + animation, what each key
    --                         triggers, i-frame candidates. Rewritten every 30 s and on stop.
    --   timeline_<time>.txt   everything in order, human readable
    --   events_<time>.jsonl   everything as data (one JSON object per line) for offline analysis
    --
    -- KEYS:  End = stop + final summary    Insert = drop a MARK line ("that one hit me")
    --        Delete = flush files now
    -- Re-running the script stops the previous instance first.

    local Players           = game:GetService("Players")
    local Workspace         = game:GetService("Workspace")
    local ReplicatedStorage = game:GetService("ReplicatedStorage")
    local HttpService       = game:GetService("HttpService")
    local UIS               = game:GetService("UserInputService")

    local LP = Players.LocalPlayer

    --------------------------------------------------------------------- settings

    local RADIUS         = 90     -- ignore mobs / parts further than this from you (studs)
    local PROJ_RADIUS    = 300    -- projectiles are checked from further out (long-range shots)
    local NEAR           = 35     -- "near me" for the summary tables
    local HIT_WINDOW     = 3.0    -- damage this long after an attack anim started can be blamed on it
    local KEY_WINDOW     = 0.5    -- your anims/remotes/state this soon after a key belong to that key
    local HOOK_REMOTES   = false  -- hook __namecall to log your own FireServer calls. OFF: the hook itself
                                  -- is the detectable part, and the auto-dodge presses keys, never remotes
    local FLUSH_EVERY    = 1.5    -- seconds between file appends
    local SUMMARY_EVERY  = 30     -- seconds between summary rewrites
    local EVENTS_PER_SEC = 300    -- hard cap so a boss fight can never tank your framerate
    local PARTS_PER_SEC  = 120    -- new-part inspections per second
    local MUTE_AFTER     = 40     -- a noisy attribute / child / remote stops being logged after this many

    local GUI_WORDS = { "weave", "stack", "dodge", "evade", "perfect", "stamina", "dash", "parry", "miss", "iframe" }
    local VALUE_WORDS = { "stamina", "weave", "dodge", "iframe", "invinc", "stun", "dash", "combat", "block",
                          "parry", "energy", "posture", "evade", "roll", "ragdoll" }

    local DIR      = "Veil_Combat"
    local SESSION  = os.date("%m%d_%H%M%S")
    local TIMELINE = DIR .. "/timeline_" .. SESSION .. ".txt"
    local EVENTS   = DIR .. "/events_" .. SESSION .. ".jsonl"
    local SUMMARY  = DIR .. "/summary_" .. SESSION .. ".txt"

    --------------------------------------------------------------------- one instance only

    local G = getgenv and getgenv() or _G
    if G.VeilCombatRecorder then pcall(G.VeilCombatRecorder.stop, "restarted") end
    local SELF = { running = true }
    G.VeilCombatRecorder = SELF

    if makefolder and isfolder and not isfolder(DIR) then pcall(makefolder, DIR) end

    --------------------------------------------------------------------- output

    local t0 = os.clock()
    local function now() return os.clock() - t0 end
    local function r2(x) return math.floor(x * 100 + 0.5) / 100 end

    local tl_buf, ev_buf = {}, {}
    local tl_all, ev_all = {}, {}
    local have_append = type(appendfile) == "function"
    local ev_count, ev_sec, ev_sec_at, dropped = 0, 0, 0, 0
    local last_line = "waiting"

    local function emit(kind, data, text)
        if not SELF.running then return end
        local t = now()
        if t - ev_sec_at >= 1 then ev_sec, ev_sec_at = 0, t end
        ev_sec += 1
        if ev_sec > EVENTS_PER_SEC and kind ~= "HIT" and kind ~= "part" and kind ~= "partgone" then
            dropped += 1; return
        end
        ev_count += 1
        data = data or {}
        data.k = kind
        data.t = math.floor(t * 1000) / 1000
        local ok, enc = pcall(HttpService.JSONEncode, HttpService, data)
        if ok then ev_buf[#ev_buf + 1] = enc end
        if text then
            local line = string.format("%8.3f  %-8s %s", t, kind, text)
            tl_buf[#tl_buf + 1] = line
            last_line = line
        end
    end

    local function write_chunk(path, buf, all)
        if #buf == 0 or not writefile then return end
        local chunk = table.concat(buf, "\n") .. "\n"
        if have_append then
            -- a failed append (file open in another program) keeps the lines for the next flush.
            -- NEVER fall back to writefile here: that would replace the whole log with one chunk.
            if pcall(appendfile, path, chunk) then table.clear(buf) end
            if #buf > 20000 then table.clear(buf) end   -- stuck for a long time: drop, don't balloon
            return
        end
        table.clear(buf)
        do
            all[#all + 1] = chunk
            pcall(writefile, path, table.concat(all))
        end
    end

    local function flush()
        write_chunk(TIMELINE, tl_buf, tl_all)
        write_chunk(EVENTS, ev_buf, ev_all)
    end

    if writefile then
        pcall(writefile, TIMELINE, "Veil combat recorder -- " .. os.date("%Y-%m-%d %H:%M:%S") ..
            "   (seconds since start | kind | detail)\n")
        pcall(writefile, EVENTS, "")
    end

    --------------------------------------------------------------------- helpers

    local function root()
        local c = LP.Character
        return c and (c:FindFirstChild("HumanoidRootPart") or c.PrimaryPart)
    end

    local function flat(v) return Vector3.new(v.X, 0, v.Z) end

    -- degrees between where cf is looking and the direction to pos (0 = straight at it)
    local function facing(cf, pos)
        local look, to = flat(cf.LookVector), flat(pos - cf.Position)
        if look.Magnitude < 1e-3 or to.Magnitude < 1e-3 then return 0 end
        return math.deg(math.acos(math.clamp(look.Unit:Dot(to.Unit), -1, 1)))
    end

    local function has_word(s, words)
        s = string.lower(s or "")
        for _, w in ipairs(words) do
            if string.find(s, w, 1, true) then return true end
        end
        return false
    end

    local function median(t)
        if #t == 0 then return nil end
        local c = table.clone(t)
        table.sort(c)
        local m = math.floor(#c / 2)
        return #c % 2 == 1 and c[m + 1] or (c[m] + c[m + 1]) / 2
    end

    local function minmax(t)
        local lo, hi = math.huge, -math.huge
        for _, v in ipairs(t) do lo = math.min(lo, v); hi = math.max(hi, v) end
        if lo == math.huge then return nil, nil end
        return lo, hi
    end

    local function str(v)
        local ty = typeof(v)
        if ty == "number" then return tostring(r2(v)) end
        if ty == "Instance" then return "<" .. v.ClassName .. ":" .. v.Name .. ">" end
        if ty == "Vector3" then return string.format("V3(%.1f,%.1f,%.1f)", v.X, v.Y, v.Z) end
        if ty == "CFrame" then local p = v.Position return string.format("CF(%.1f,%.1f,%.1f)", p.X, p.Y, p.Z) end
        return tostring(v)
    end

    local mobs = {}   -- model -> info (declared early so repr can name them)
    local DEEP = false   -- repr detail switch (TweenEffectEvent payloads are logged in full)

    -- short readable form of remote arguments
    local function repr(v, depth)
        depth = depth or 0
        local ty = typeof(v)
        if ty == "string" then
            local cap = DEEP and 200 or 60
            return string.format("%q", #v > cap and (string.sub(v, 1, cap) .. "...") or v)
        elseif ty == "Instance" then
            local ok, s = pcall(function()
                if v == LP.Character or v == LP then return "<ME>" end
                if mobs[v] then return "<mob:" .. mobs[v].label .. "#" .. mobs[v].uid .. ">" end
                return "<" .. v.ClassName .. ":" .. v.Name .. ">"
            end)
            return ok and s or "<Instance>"
        elseif ty == "table" then
            if depth >= (DEEP and 4 or 2) then return "{...}" end
            local parts, n = {}, 0
            for k, val in pairs(v) do
                n += 1
                if n > (DEEP and 24 or 8) then parts[#parts + 1] = "..."; break end
                parts[#parts + 1] = (type(k) == "string" and (k .. "=") or "") .. repr(val, depth + 1)
            end
            return "{" .. table.concat(parts, ", ") .. "}"
        end
        return str(v)
    end

    local function repr_args(...)
        local n = select("#", ...)
        local out = {}
        for i = 1, math.min(n, 8) do out[i] = repr((select(i, ...))) end
        if n > 8 then out[#out + 1] = "..." end
        return table.concat(out, ", ")
    end

    local conns = {}
    local function keep(c) conns[#conns + 1] = c; return c end

    --------------------------------------------------------------------- aggregates (for the summary)

    local stats = {}        -- "mob | animId" -> per-attack numbers
    local keystats = {}     -- key -> { n, follow = { what -> count } }
    local mychild = {}      -- name -> { n, lifes, keys }
    local rin, rout = {}, {}   -- remote name -> count
    local unblamed = { n = 0, dmg = 0 }
    local hits_total, attacks_total = 0, 0
    local pings = {}

    local function stat(label, id, name)
        local key = label .. "  |  " .. id
        local s = stats[key]
        if not s then
            s = { mob = label, id = id, name = name, plays = 0, near = 0, hits = 0, extra_hits = 0,
                  delays = {}, dmg = {}, dists = {}, len = 0, looped = false, prio = "",
                  hitbox_at = {}, proj_eta = {}, sounds = {}, kf = {}, attrs = {},
                  box_lead = {}, amb = 0, clean = 0, clean_keys = {}, odelays = {}, ohits = 0, ovictims = {} }
            stats[key] = s
        end
        return s
    end

    --------------------------------------------------------------------- my key presses

    local recent_keys = {}   -- { key, t }
    local live_attacks = {}  -- attack records still inside HIT_WINDOW

    -- the key pressed most recently, if it was inside KEY_WINDOW
    local function last_key()
        local k = recent_keys[#recent_keys]
        if k and now() - k.t <= KEY_WINDOW then return k.key, now() - k.t end
        return nil, nil
    end

    -- credit something I did to the key that most likely caused it
    local function follow(what)
        local key, dt = last_key()
        if key and keystats[key] then
            local f = keystats[key].follow
            f[what] = (f[what] or 0) + 1
        end
        return key, dt
    end

    local function key_note()
        local key, dt = last_key()
        if key then return string.format("  [%.2fs after %s]", dt, key), key, dt end
        return "", nil, nil
    end

    --------------------------------------------------------------------- mobs

    local mob_seq = 0

    local function is_summon(model)
        if tonumber(model.Name) then return true end
        for _, d in ipairs(model:GetChildren()) do
            if d:IsA("BillboardGui") and d.Name == "SummonNameGui" then return true end
        end
        return model:FindFirstChild("PlayerID") ~= nil
    end

    local function mob_label(model)
        local t = model:GetAttribute("MobType")
        return (type(t) == "string" and t ~= "") and t or model.Name
    end

    local function mob_dist(info)
        local r = root()
        if not r or not info.root.Parent then return math.huge end
        return (info.root.Position - r.Position).Magnitude
    end

    -- the attack this mob started most recently, if it is still inside the hit window
    local function since_attack(info)
        local a = info and info.last
        if a and now() - a.t <= HIT_WINDOW then return now() - a.t, a end
        return nil, nil
    end

    local function nearest_mob(pos)
        local best, bestd
        for _, info in pairs(mobs) do
            if info.root.Parent then
                local d = (info.root.Position - pos).Magnitude
                if not bestd or d < bestd then best, bestd = info, d end
            end
        end
        return best, bestd
    end

    local function attrs_of(inst)
        local out, n = {}, 0
        for k, v in pairs(inst:GetAttributes()) do
            n += 1
            if n > 12 then break end
            out[k] = str(v)
        end
        return out
    end

    local LOCO = { Core = true, Idle = true, Movement = true }

    local function on_mob_anim(info, track)
        local r = root()
        if not r or not info.root.Parent then return end
        local dist = (info.root.Position - r.Position).Magnitude
        if dist > RADIUS then return end

        local anim = track.Animation
        local id = anim and anim.AnimationId or "?"
        local name = (anim and anim.Name ~= "Animation" and anim.Name) or track.Name
        local prio = track.Priority.Name
        local s = stat(info.label, id, name)
        s.plays += 1
        s.looped, s.prio = track.Looped, prio
        if track.Length > 0 then s.len = track.Length end
        -- idle / walk / run: counted so the summary can list them, never logged line by line
        if track.Looped and LOCO[prio] then return end

        local t = now()
        attacks_total += 1
        if dist <= NEAR then s.near += 1 end
        s.dists[#s.dists + 1] = r2(dist)

        local face = facing(info.root.CFrame, r.Position)
        local to = flat(r.Position - info.root.Position)
        local closing = to.Magnitude > 0.1 and flat(info.root.AssemblyLinearVelocity):Dot(to.Unit) or 0

        local atk = { info = info, s = s, id = id, name = name, t = t, dist = dist, keys = {}, hits = 0,
                      face = face }
        info.last = atk
        live_attacks[#live_attacks + 1] = atk

        emit("anim", { mob = info.label, uid = info.uid, id = id, name = name, len = r2(track.Length),
                       prio = prio, looped = track.Looped, speed = r2(track.Speed), dist = r2(dist),
                       face = math.floor(face), closing = r2(closing), attrs = attrs_of(info.model) },
            string.format("%s#%d  %s  %s  len %.2f  %s%s  dist %.1f  facing %d deg  closing %.1f",
                info.label, info.uid, name, id, track.Length, prio, track.Looped and " looped" or "",
                dist, face, closing))

        if track.Length == 0 then
            task.delay(0.3, function()
                if track.Length > 0 then s.len = track.Length end
            end)
        end

        local kc, sc
        pcall(function()
            kc = track.KeyframeReached:Connect(function(kf)
                local dt = now() - t
                s.kf[kf] = s.kf[kf] or {}
                table.insert(s.kf[kf], dt)
                emit("keyframe", { mob = info.label, uid = info.uid, id = id, kf = kf, at = r2(dt) },
                    string.format("%s#%d  %s  keyframe %q at %.2fs", info.label, info.uid, name, kf, dt))
            end)
        end)
        sc = track.Stopped:Connect(function()
            atk.dur = now() - t
            emit("animend", { mob = info.label, uid = info.uid, id = id, dur = r2(atk.dur) })
            if kc then kc:Disconnect() end
            if sc then sc:Disconnect() end
        end)
        task.delay(12, function()
            if kc then pcall(function() kc:Disconnect() end) end
            if sc then pcall(function() sc:Disconnect() end) end
        end)
    end

    local function hook_sound(info, snd)
        local function played()
            if mob_dist(info) > RADIUS then return end
            local dt, atk = since_attack(info)
            local sid = snd.SoundId ~= "" and snd.SoundId or "?"
            if atk then
                local key = snd.Name .. " " .. sid
                atk.s.sounds[key] = atk.s.sounds[key] or {}
                table.insert(atk.s.sounds[key], dt)
            end
            emit("sound", { mob = info.label, uid = info.uid, name = snd.Name, id = sid,
                            atk = atk and atk.id or nil, since = dt and r2(dt) or nil },
                string.format("%s#%d  sound %s %s%s", info.label, info.uid, snd.Name, sid,
                    dt and string.format("  %.2fs into %s", dt, atk.name) or ""))
        end
        table.insert(info.conns, snd.Played:Connect(played))
        if snd.IsPlaying then played() end
    end

    local function on_mob_attr(info, inst, attr)
        if mob_dist(info) > RADIUS then return end
        local c = (info.attr_n[attr] or 0) + 1
        info.attr_n[attr] = c
        if c > MUTE_AFTER then
            if c == MUTE_AFTER + 1 then emit("muted", { what = "mob attr " .. attr }, info.label .. "  attr " .. attr .. " is noisy, muted") end
            return
        end
        local v = inst:GetAttribute(attr)
        local dt, atk = since_attack(info)
        if atk then
            local key = attr .. "=" .. str(v)
            atk.s.attrs[key] = atk.s.attrs[key] or {}
            table.insert(atk.s.attrs[key], dt)
        end
        emit("mobattr", { mob = info.label, uid = info.uid, on = inst.ClassName, attr = attr, v = str(v),
                          atk = atk and atk.id or nil, since = dt and r2(dt) or nil },
            string.format("%s#%d  attr %s = %s%s", info.label, info.uid, attr, str(v),
                dt and string.format("  (%.2fs into %s)", dt, atk.name) or ""))
    end

    local SKIP_MOB_CHILD = { Motor6D = true, Weld = true, WeldConstraint = true, Attachment = true,
                             Animation = true, AnimationTrack = true }

    local function on_mob_desc(info, d)
        if d:IsA("Sound") then hook_sound(info, d); return end
        if d:IsA("BasePart") or SKIP_MOB_CHILD[d.ClassName] then return end   -- parts: global watcher
        if mob_dist(info) > RADIUS then return end
        local c = (info.child_n[d.Name] or 0) + 1
        info.child_n[d.Name] = c
        if c > MUTE_AFTER then return end
        local born = now()
        local dt, atk = since_attack(info)
        emit("mobchild", { mob = info.label, uid = info.uid, class = d.ClassName, name = d.Name,
                           atk = atk and atk.id or nil, since = dt and r2(dt) or nil },
            string.format("%s#%d  + %s %s%s", info.label, info.uid, d.ClassName, d.Name,
                dt and string.format("  (%.2fs into %s)", dt, atk.name) or ""))
        local ac
        ac = d.AncestryChanged:Connect(function()
            if d:IsDescendantOf(info.model) then return end
            ac:Disconnect()
            emit("mobchildgone", { mob = info.label, uid = info.uid, name = d.Name, life = r2(now() - born) },
                string.format("%s#%d  - %s after %.2fs", info.label, info.uid, d.Name, now() - born))
        end)
        task.delay(20, function() pcall(function() ac:Disconnect() end) end)
    end

    local function unregister(model)
        local info = mobs[model]
        if not info then return end
        mobs[model] = nil
        for _, c in ipairs(info.conns) do pcall(function() c:Disconnect() end) end
    end

    local function register(model)
        if mobs[model] or not model:IsA("Model") then return end
        if model == LP.Character or Players:GetPlayerFromCharacter(model) then return end
        local hum = model:FindFirstChildOfClass("Humanoid")
        local rp = model:FindFirstChild("HumanoidRootPart") or model.PrimaryPart
        if not hum or not rp or hum.MaxHealth >= 1e6 or is_summon(model) then return end
        local animator = model:FindFirstChildWhichIsA("Animator", true)
        local isBoss = string.sub(model.Name, 1, 4) == "The " or string.find(model.Name, "Festering", 1, true) ~= nil
        if not animator and not isBoss then return end   -- the scan loop retries until it exists

        mob_seq += 1
        local info = { model = model, hum = hum, root = rp, uid = mob_seq, label = mob_label(model),
                       conns = {}, attr_n = {}, child_n = {} }
        mobs[model] = info
        local function c(sig, fn) table.insert(info.conns, sig:Connect(function(...) pcall(fn, ...) end)) end
        if animator then c(animator.AnimationPlayed, function(tr) on_mob_anim(info, tr) end) end
        if isBoss then
            -- bosses: position / velocity / health 10x a second while near you (slams, charges,
            -- ground strikes show up in the motion even when no animation is visible)
            task.spawn(function()
                while SELF.running and model.Parent and rp.Parent do
                    local r = root()
                    if r and (rp.Position - r.Position).Magnitude < 150 then
                        local v = rp.AssemblyLinearVelocity
                        emit("bosspos", { mob = info.label, uid = info.uid,
                                          pos = { r2(rp.Position.X), r2(rp.Position.Y), r2(rp.Position.Z) },
                                          vel = { r2(v.X), r2(v.Y), r2(v.Z) },
                                          dist = r2((rp.Position - r.Position).Magnitude), hp = r2(hum.Health) })
                    end
                    task.wait(0.1)
                end
            end)
        end
        c(model.AttributeChanged, function(a) on_mob_attr(info, model, a) end)
        c(hum.AttributeChanged, function(a) on_mob_attr(info, hum, a) end)
        c(rp.AttributeChanged, function(a) on_mob_attr(info, rp, a) end)
        c(model.DescendantAdded, function(d) on_mob_desc(info, d) end)
        c(hum.Died, function() unregister(model) end)
        c(model.AncestryChanged, function(_, p) if not p then unregister(model) end end)
        for _, d in ipairs(model:GetDescendants()) do
            if d:IsA("Sound") then pcall(hook_sound, info, d) end
        end
    end

    --------------------------------------------------------------------- other victims
    -- Mobs hitting your summons and other players give the same "damage lands X s after the
    -- animation starts" numbers as hits on you, without you having to eat them.

    local victims = {}   -- humanoid -> true
    local ohits_total = 0

    local function register_victim(model, kind)
        local hum = model:FindFirstChildOfClass("Humanoid")
        local vr = model:FindFirstChild("HumanoidRootPart") or model.PrimaryPart
        if not hum or not vr or victims[hum] then return end
        victims[hum] = true
        local last = hum.Health
        local c1, c2
        c1 = hum.HealthChanged:Connect(function(new)
            local drop = last - new
            last = new
            if drop <= 0.01 or not SELF.running or not vr.Parent then return end
            local r = root()
            if not r or (vr.Position - r.Position).Magnitude > RADIUS then return end
            local t = now()
            -- the mob closest to the VICTIM with a live attack, most recent start on ties
            local best, bestd
            for _, atk in ipairs(live_attacks) do
                local dt = t - atk.t
                if dt >= 0 and dt <= HIT_WINDOW and atk.info.root.Parent then
                    local d = (atk.info.root.Position - vr.Position).Magnitude
                    if d <= 30 and (not best or d < bestd - 0.5 or (math.abs(d - bestd) <= 0.5 and atk.t > best.t)) then
                        best, bestd = atk, d
                    end
                end
            end
            if not best then return end   -- your own poison / your hits on things are not our business
            local dt = t - best.t
            best.ohits = (best.ohits or 0) + 1
            if best.ohits == 1 then
                table.insert(best.s.odelays, dt)
                best.s.ohits += 1
                best.s.ovictims[kind] = (best.s.ovictims[kind] or 0) + 1
            end
            ohits_total += 1
            emit("OHIT", { victim = model.Name, kind = kind, dmg = r2(drop), mob = best.info.label,
                           uid = best.info.uid, id = best.id, name = best.name, delay = r2(dt),
                           nth = best.ohits, mob_dist = r2(bestd) },
                string.format("%s %s -%.1f  <- %s#%d %s  %.2fs after it started (%.0f studs)",
                    kind, model.Name, drop, best.info.label, best.info.uid, best.name, dt, bestd))
        end)
        c2 = model.AncestryChanged:Connect(function(_, p)
            if p then return end
            victims[hum] = nil
            c1:Disconnect(); c2:Disconnect()
        end)
        keep(c1); keep(c2)
    end

    local function scan_victims()
        for _, pl in ipairs(Players:GetPlayers()) do
            if pl ~= LP and pl.Character then pcall(register_victim, pl.Character, "player") end
        end
        local folder = Workspace:FindFirstChild("Monsters")
        if folder then
            for _, m in ipairs(folder:GetChildren()) do
                if m:IsA("Model") and is_summon(m) then pcall(register_victim, m, "summon") end
            end
        end
    end

    local last_wide = 0
    local function scan_mobs()
        pcall(scan_victims)
        local folder = Workspace:FindFirstChild("Monsters")
        if folder then
            for _, m in ipairs(folder:GetChildren()) do pcall(register, m) end
        end
        -- bosses / event mobs that might live outside Monsters
        if not folder or now() - last_wide > 5 then
            last_wide = now()
            for _, m in ipairs(Workspace:GetChildren()) do
                if m:IsA("Model") and m:FindFirstChildOfClass("Humanoid") then pcall(register, m) end
            end
        end
    end

    --------------------------------------------------------------------- parts: hitboxes + projectiles

    local HINTS = { "hitbox", "hurtbox", "damage", "dmg", "hit", "attack", "swing", "slash", "strike",
                    "blast", "shockwave", "aoe", "zone", "explosion", "projectile", "bullet", "laser",
                    "beam", "spike", "stomp", "slam", "orb", "ball", "wave" }

    local function part_score(part)
        local s, why = 0, {}
        local n = string.lower(part.Name)
        for _, h in ipairs(HINTS) do
            if string.find(n, h, 1, true) then s += 4; why[#why + 1] = "name:" .. h; break end
        end
        if not part.CanCollide then s += 1; why[#why + 1] = "nocollide" end
        if part.Transparency >= 0.9 then s += 2; why[#why + 1] = "invisible"
        elseif part.Transparency >= 0.5 then s += 1; why[#why + 1] = "seethrough" end
        if part.CanTouch then s += 1; why[#why + 1] = "cantouch" end
        if part.Anchored then s += 1; why[#why + 1] = "anchored" end
        local v = part.Size
        if math.max(v.X, v.Y, v.Z) >= 3 then s += 1; why[#why + 1] = "big" end
        if part.CanCollide and part.Transparency < 0.5 and s < 4 then return 0, why end
        return s, why
    end

    local function covers(part, pos, pad)
        local rel = part.CFrame:PointToObjectSpace(pos)
        local h = part.Size * 0.5
        return math.abs(rel.X) <= h.X + pad and math.abs(rel.Y) <= h.Y + pad and math.abs(rel.Z) <= h.Z + pad
    end

    local recent_proj = {}   -- projectiles on course for me, for damage blaming
    local recent_cover = {}  -- parts that covered me: { born, rec } -> "hitbox seen X s before the hit"
    local box_leads = {}     -- every such lead, for the headline number

    -- Follow a fireball's flight: position + distance to you every 0.1 s for 2 s. Tells whether
    -- it visibly moves on your client (Imp / Cambion fireballs looked frozen in one sample)
    -- and how it homes.
    local function trace_path(part)
        task.spawn(function()
            local t0p, pts = now(), {}
            local last = part.Position
            for _ = 1, 20 do
                task.wait(0.1)
                if not part.Parent or not SELF.running then break end
                local r = root()
                local p = part.Position
                pts[#pts + 1] = string.format("%.2f:%.1f,%.1f,%.1f d%.1f v%.0f", now() - t0p, p.X, p.Y, p.Z,
                    r and (p - r.Position).Magnitude or -1, (p - last).Magnitude / 0.1)
                last = p
            end
            emit("trace", { name = part.Name, size = { r2(part.Size.X), r2(part.Size.Y), r2(part.Size.Z) },
                            path = table.concat(pts, " | ") })
        end)
    end

    local function on_part(part, born)
        if part.Name == "ImpFireball" or (part.Name == "Main" and math.abs(part.Size.X - 2.5) < 0.3) then
            trace_path(part)
        end
        if not part.Parent then return end
        local r = root()
        if not r then return end
        local char = LP.Character
        if char and part:IsDescendantOf(char) then return end
        local p1 = part.Position
        local dist = (p1 - r.Position).Magnitude
        -- bombs / hitboxes can appear at a placeholder position before being moved into place,
        -- so they are never dropped for distance at spawn (the rest are re-checked below)
        local vip = string.find(part.Name, "Bomb") or string.find(part.Name, "Hitbox")
        if dist > PROJ_RADIUS and not vip then return end

        -- sample movement to spot projectiles
        task.wait(0.1)
        if not part.Parent then return end
        r = root()
        if not r then return end
        local p2 = part.Position
        local vel = (p2 - p1) / 0.1
        local speed = vel.Magnitude
        local owner = nil
        for model, info in pairs(mobs) do
            if part:IsDescendantOf(model) then owner = info; break end
        end
        -- a part carried along by its mob is not a projectile
        if owner then speed = (vel - owner.root.AssemblyLinearVelocity).Magnitude end
        local is_proj = speed > 20
        -- far away parts only count if they are flying
        if dist > RADIUS and not is_proj and not (vip and (p2 - r.Position).Magnitude <= PROJ_RADIUS) then return end

        local score, why = part_score(part)
        if score < 4 and not is_proj then return end

        local src, srcd = owner, nil
        if not src then src, srcd = nearest_mob(p1) end
        local dt, atk = since_attack(src)

        local rec = { name = part.Name, class = part.ClassName, path = part:GetFullName(),
                      size = { r2(part.Size.X), r2(part.Size.Y), r2(part.Size.Z) },
                      dist = r2((p2 - r.Position).Magnitude), score = score, why = table.concat(why, ","),
                      speed = r2(speed), mob = src and src.label or nil, uid = src and src.uid or nil,
                      in_mob = owner ~= nil, mob_dist = srcd and r2(srcd) or nil,
                      atk = atk and atk.id or nil, atk_name = atk and atk.name or nil,
                      since = dt and r2(dt + 0.1) or nil,
                      covered_me = covers(part, r.Position, 2.5) }

        local extra = ""
        if is_proj then
            -- closest approach of a straight-line flight to where I am standing
            local rel = r.Position - p2
            local tt = math.max(0, rel:Dot(vel) / (speed * speed))
            local miss = (rel - vel * tt).Magnitude
            rec.proj, rec.eta, rec.miss = true, r2(tt), r2(miss)
            rec.vel = { r2(vel.X), r2(vel.Y), r2(vel.Z) }
            extra = string.format("  PROJECTILE %.0f st/s  eta %.2fs  passes %.1f studs from me", speed, tt, miss)
            if miss < 6 then
                recent_proj[#recent_proj + 1] = { rec = rec, arrive = now() + tt }
                if atk then table.insert(atk.s.proj_eta, dt + 0.1 + tt) end
            end
        end
        if atk then table.insert(atk.s.hitbox_at, dt + 0.1) end
        if rec.covered_me then
            recent_cover[#recent_cover + 1] = { born = born, rec = rec }
            if #recent_cover > 30 then table.remove(recent_cover, 1) end
        end

        emit("part", rec, string.format("%s %s  %.1fx%.1fx%.1f  %.0f studs  %s%s%s%s",
            part.Name, part.ClassName, part.Size.X, part.Size.Y, part.Size.Z, rec.dist, rec.why,
            rec.covered_me and "  *** COVERS ME ***" or "",
            atk and string.format("  %.2fs into %s#%d %s", dt + 0.1, src.label, src.uid, atk.name) or "",
            extra))

        local ac
        ac = part.AncestryChanged:Connect(function(_, parent)
            if parent then return end
            ac:Disconnect()
            emit("partgone", { name = part.Name, life = r2(now() - born), uid = rec.uid })
        end)
        task.delay(15, function() pcall(function() ac:Disconnect() end) end)
    end

    -- global sounds (effects parented to parts / attachments rather than to the mob)
    local function on_world_sound(snd)
        local r = root()
        if not r then return end
        local function played()
            local p = snd.Parent
            local pos = p and (p:IsA("BasePart") and p.Position or (p:IsA("Attachment") and p.WorldPosition))
            if not pos or (pos - r.Position).Magnitude > RADIUS then return end
            local src = nearest_mob(pos)
            local dt, atk = since_attack(src)
            local sid = snd.SoundId ~= "" and snd.SoundId or "?"
            if atk then
                local key = snd.Name .. " " .. sid
                atk.s.sounds[key] = atk.s.sounds[key] or {}
                table.insert(atk.s.sounds[key], dt)
            end
            emit("wsound", { name = snd.Name, id = sid, mob = src and src.label or nil,
                             atk = atk and atk.id or nil, since = dt and r2(dt) or nil },
                string.format("world sound %s %s%s", snd.Name, sid,
                    dt and string.format("  %.2fs into %s#%d %s", dt, src.label, src.uid, atk.name) or ""))
        end
        local pc = snd.Played:Connect(function() pcall(played) end)
        task.delay(10, function() pcall(function() pc:Disconnect() end) end)
        if snd.IsPlaying then pcall(played) end
    end

    local looked, looked_at = 0, 0
    local monsters_folder = Workspace:FindFirstChild("Monsters")
    local drops = Workspace:FindFirstChild("Drops")
    keep(Workspace.DescendantAdded:Connect(function(inst)
        if not SELF.running then return end
        local is_part, is_sound = inst:IsA("BasePart"), inst:IsA("Sound")
        if not is_part and not is_sound then return end
        if drops and inst:IsDescendantOf(drops) then return end
        if is_sound then
            -- mob sounds are hooked per mob
            monsters_folder = monsters_folder or Workspace:FindFirstChild("Monsters")
            if monsters_folder and inst:IsDescendantOf(monsters_folder) then return end
            task.defer(function() pcall(on_world_sound, inst) end)
            return
        end
        local t = now()
        if t - looked_at >= 1 then looked, looked_at = 0, t end
        looked += 1
        -- bombs / hitboxes are the whole point: never rate-limit them (a Puppeteer fight
        -- throws hundreds of other parts and the cap was eating bombs)
        local vip = string.find(inst.Name, "Bomb") or string.find(inst.Name, "Hitbox")
        if looked > PARTS_PER_SEC and not vip then return end
        task.delay(0.03, function()
            if SELF.running then pcall(on_part, inst, t) end
        end)
    end))

    --------------------------------------------------------------------- damage to me

    local last_hp = nil

    local function on_health(hum, new)
        local old = last_hp or hum.MaxHealth
        last_hp = new
        local drop = old - new
        if drop <= 0.01 then return end
        local t = now()
        local r = root()

        -- blame: score every live attack by how close its mob is now, heavily penalising mobs
        -- that were facing away when they started swinging. Per mob only its latest attack counts.
        local per_mob = {}
        for _, atk in ipairs(live_attacks) do
            local dt = t - atk.t
            if dt >= 0 and dt <= HIT_WINDOW then
                local cur = per_mob[atk.info]
                if not cur or atk.t > cur.t then per_mob[atk.info] = atk end
            end
        end
        local ranked = {}
        for _, atk in pairs(per_mob) do
            local d = mob_dist(atk.info)
            if d == math.huge then d = atk.dist end
            local pen = (atk.face or 0) > 90 and 20 or ((atk.face or 0) > 45 and 6 or 0)
            ranked[#ranked + 1] = { atk = atk, d = d, score = d + pen }
        end
        table.sort(ranked, function(a, b) return a.score < b.score end)
        local best, bestd = ranked[1] and ranked[1].atk, ranked[1] and ranked[1].d
        -- horde: a second mob about as likely -> log the suspects, keep it out of the timing numbers
        local ambiguous = ranked[2] ~= nil and ranked[2].score - ranked[1].score < 5
        local suspects = {}
        if ambiguous then
            for i = 1, math.min(4, #ranked) do
                local a = ranked[i].atk
                suspects[i] = string.format("%s#%d %s %.2fs %.0fst", a.info.label, a.info.uid, a.name, t - a.t, ranked[i].d)
            end
        end
        -- a projectile arriving right now beats a melee guess
        local proj
        for i = #recent_proj, 1, -1 do
            local p = recent_proj[i]
            if math.abs(t - p.arrive) <= 0.35 then proj = p.rec; break end
            if t - p.arrive > 1 then table.remove(recent_proj, i) end
        end

        -- did a part that covers me show up BEFORE this hit? (the "just dodge on hitbox" test)
        local box, box_lead
        for i = #recent_cover, 1, -1 do
            local c = recent_cover[i]
            local lead = t - c.born
            if lead >= 0 and lead <= 1.5 then box, box_lead = c.rec, lead; break end
        end
        if box_lead then box_leads[#box_leads + 1] = box_lead end

        local keys = {}
        for _, k in ipairs(recent_keys) do
            if t - k.t <= 1 then keys[#keys + 1] = k.key .. "@-" .. string.format("%.2f", t - k.t) end
        end
        local knote = #keys > 0 and ("  keys " .. table.concat(keys, " ")) or ""

        local data = { dmg = r2(drop), hp = r2(new), max = r2(hum.MaxHealth), keys = keys,
                       state = hum:GetState().Name, ws = r2(hum.WalkSpeed) }
        if best then
            local dt = t - best.t
            best.hits += 1
            hits_total += 1
            if ambiguous then
                best.s.amb += 1
                data.ambiguous = suspects
            elseif best.hits == 1 then
                best.s.hits += 1
                table.insert(best.s.delays, dt)
                table.insert(best.s.dmg, drop)
            else
                best.s.extra_hits += 1
            end
            data.mob, data.uid, data.id, data.name = best.info.label, best.info.uid, best.id, best.name
            data.delay, data.nth, data.mob_dist = r2(dt), best.hits, r2(bestd)
        else
            unblamed.n += 1
            unblamed.dmg += drop
        end
        if proj then data.proj = proj.name; data.proj_mob = proj.mob end
        if box then
            data.box, data.box_lead = box.name, r2(box_lead)
            if best and not ambiguous then table.insert(best.s.box_lead, box_lead) end
        end

        emit("HIT", data, string.format("-%.1f HP (%.0f/%.0f)  %s%s%s",
            drop, new, hum.MaxHealth,
            best and string.format("<- %s#%d %s  %.2fs after it started%s  (%.0f studs)",
                best.info.label, best.info.uid, best.name, t - best.t,
                (best.hits > 1 and (" hit #" .. best.hits) or "") ..
                    (ambiguous and ("  AMBIGUOUS: " .. table.concat(suspects, " | ")) or ""), bestd)
                or "<- no attack in window (DoT / environment / server-side)",
            (proj and ("  [projectile " .. proj.name .. "]") or "") ..
                (box and string.format("  [hitbox %s seen %.2fs before]", box.name, box_lead) or "  [no hitbox seen before it]"),
            knote))
    end

    --------------------------------------------------------------------- my character

    local char_conns = {}
    local function ckeep(c) char_conns[#char_conns + 1] = c; return c end

    local my_attr_n, my_attr_up = {}, {}
    local function on_my_attr(inst, attr, old_vals)
        local v = inst:GetAttribute(attr)
        local old = old_vals[attr]
        old_vals[attr] = v
        local id = inst.ClassName .. "." .. attr
        local t = now()
        -- numbers creeping upward (stamina regen) get logged at most once a second
        if type(v) == "number" and type(old) == "number" and v > old then
            if t - (my_attr_up[id] or -1) < 1 then return end
            my_attr_up[id] = t
        end
        local c = (my_attr_n[id] or 0) + 1
        my_attr_n[id] = c
        if c > MUTE_AFTER * 25 then return end
        local knote, key = key_note()
        local delta = (type(v) == "number" and type(old) == "number") and (v - old) or nil
        local label = type(v) == "boolean" and (attr .. "=" .. tostring(v)) or attr
        if key then follow("attr " .. label) end
        emit("myattr", { on = inst.ClassName, attr = attr, v = str(v), old = old ~= nil and str(old) or nil,
                         delta = delta and r2(delta) or nil, key = key },
            string.format("%s.%s = %s%s%s", inst.ClassName, attr, str(v),
                delta and string.format(" (%+.2f)", delta) or "", knote))
    end

    local function watch_attrs(inst)
        local vals = inst:GetAttributes()
        ckeep(inst.AttributeChanged:Connect(function(a) pcall(on_my_attr, inst, a, vals) end))
    end

    local function watch_value(v, where)
        local last = v.Value
        local last_up = -1
        ckeep(v.Changed:Connect(function(new)
            local t = now()
            if type(new) == "number" and type(last) == "number" and new > last then
                if t - last_up < 1 then last = new; return end
                last_up = t
            end
            local knote, key = key_note()
            if key then follow("value " .. v.Name .. (type(new) == "boolean" and ("=" .. tostring(new)) or "")) end
            emit("myvalue", { where = where, name = v.Name, v = str(new), old = str(last), key = key },
                string.format("%s %s = %s (was %s)%s", where, v.Name, str(new), str(last), knote))
            last = new
        end))
    end

    local my_child_n = {}
    local function on_my_desc(char, d)
        if d:IsA("Sound") then return end
        if d:IsA("ValueBase") then pcall(watch_value, d, "char") end
        local cls = d.ClassName
        local interesting = d:IsA("ValueBase") or d:IsA("Folder") or d:IsA("ForceField") or d:IsA("Highlight")
            or d:IsA("Configuration") or d:IsA("BodyMover") or d:IsA("Constraint") or d:IsA("BaseScript")
        local c = (my_child_n[d.Name] or 0) + 1
        my_child_n[d.Name] = c
        if not interesting and c > 20 then return end
        local born = now()
        local knote, key, kdt = key_note()
        local mc = mychild[cls .. " " .. d.Name]
        if not mc then mc = { n = 0, lifes = {}, keys = {} }; mychild[cls .. " " .. d.Name] = mc end
        mc.n += 1
        if key then
            mc.keys[key] = (mc.keys[key] or 0) + 1
            follow("child " .. d.Name)
        end
        emit("mychild", { class = cls, name = d.Name, parent = d.Parent and d.Parent.Name or nil,
                          key = key, after_key = kdt and r2(kdt) or nil },
            string.format("+ %s %s (in %s)%s", cls, d.Name, d.Parent and d.Parent.Name or "?", knote))
        local ac
        ac = d.AncestryChanged:Connect(function()
            if d:IsDescendantOf(char) then return end
            ac:Disconnect()
            local life = now() - born
            table.insert(mc.lifes, life)
            emit("mychildgone", { class = cls, name = d.Name, life = r2(life) },
                string.format("- %s %s after %.2fs", cls, d.Name, life))
        end)
        task.delay(30, function() pcall(function() ac:Disconnect() end) end)
    end

    local my_anims = {}   -- id -> { name, n, keys = {key -> {dt}} , len }
    local function on_my_anim(track)
        local anim = track.Animation
        local id = anim and anim.AnimationId or "?"
        local name = (anim and anim.Name ~= "Animation" and anim.Name) or track.Name
        local prio = track.Priority.Name
        if track.Looped and LOCO[prio] then return end
        local knote, key, kdt = key_note()
        local a = my_anims[id]
        if not a then a = { name = name, n = 0, keys = {}, len = 0 }; my_anims[id] = a end
        a.n += 1
        if track.Length > 0 then a.len = track.Length end
        if key then
            a.keys[key] = a.keys[key] or {}
            table.insert(a.keys[key], kdt)
            follow("anim " .. name)
        end
        emit("myanim", { id = id, name = name, len = r2(track.Length), prio = prio, looped = track.Looped,
                         key = key, after_key = kdt and r2(kdt) or nil },
            string.format("ME  %s  %s  len %.2f  %s%s", name, id, track.Length, prio, knote))
        if track.Length == 0 then
            task.delay(0.3, function() if track.Length > 0 then a.len = track.Length end end)
        end
    end

    local function hook_character(char)
        for _, c in ipairs(char_conns) do pcall(function() c:Disconnect() end) end
        table.clear(char_conns)
        local hum = char:WaitForChild("Humanoid", 10)
        if not hum or not SELF.running then return end
        last_hp = hum.Health
        emit("spawn", { hp = r2(hum.Health), max = r2(hum.MaxHealth), ws = r2(hum.WalkSpeed),
                        jp = r2(hum.JumpPower), attrs = attrs_of(char) },
            string.format("character spawned  hp %.0f/%.0f  walkspeed %.1f", hum.Health, hum.MaxHealth, hum.WalkSpeed))

        ckeep(hum.HealthChanged:Connect(function(v) pcall(on_health, hum, v) end))
        ckeep(hum.StateChanged:Connect(function(old, new)
            if new == Enum.HumanoidStateType.Running or new == Enum.HumanoidStateType.RunningNoPhysics then return end
            local knote, key = key_note()
            if key then follow("state " .. new.Name) end
            emit("mystate", { from = old.Name, to = new.Name, key = key },
                string.format("state %s -> %s%s", old.Name, new.Name, knote))
        end))
        for _, prop in ipairs({ "WalkSpeed", "JumpPower", "JumpHeight", "AutoRotate", "PlatformStand", "Sit" }) do
            local last = hum[prop]
            ckeep(hum:GetPropertyChangedSignal(prop):Connect(function()
                local v = hum[prop]
                local knote, key = key_note()
                if key then follow("prop " .. prop .. "=" .. str(v)) end
                emit("myprop", { prop = prop, v = str(v), old = str(last), key = key },
                    string.format("%s %s -> %s%s", prop, str(last), str(v), knote))
                last = v
            end))
        end

        watch_attrs(char)
        watch_attrs(hum)
        local hrp = char:FindFirstChild("HumanoidRootPart")
        if hrp then watch_attrs(hrp) end

        local animator = hum:FindFirstChildOfClass("Animator") or hum:WaitForChild("Animator", 5)
        if animator then ckeep(animator.AnimationPlayed:Connect(function(tr) pcall(on_my_anim, tr) end)) end

        for _, d in ipairs(char:GetDescendants()) do
            if d:IsA("ValueBase") then pcall(watch_value, d, "char") end
        end
        ckeep(char.DescendantAdded:Connect(function(d) pcall(on_my_desc, char, d) end))
    end

    if LP.Character then task.spawn(hook_character, LP.Character) end
    keep(LP.CharacterAdded:Connect(function(c) task.spawn(hook_character, c) end))

    -- player-level attributes + combat-sounding values (stamina / weave might live here, not on the rig)
    do
        local vals = LP:GetAttributes()
        keep(LP.AttributeChanged:Connect(function(a) pcall(on_my_attr, LP, a, vals) end))
        local function maybe_value(d)
            if d:IsA("ValueBase") and has_word(d.Name, VALUE_WORDS) then
                local last, last_up = d.Value, -1
                keep(d.Changed:Connect(function(new)
                    local t = now()
                    if type(new) == "number" and type(last) == "number" and new > last then
                        if t - last_up < 1 then last = new; return end
                        last_up = t
                    end
                    local knote, key = key_note()
                    if key then follow("value " .. d.Name) end
                    emit("plvalue", { path = d:GetFullName(), v = str(new), old = str(last), key = key },
                        string.format("%s = %s (was %s)%s", d:GetFullName(), str(new), str(last), knote))
                    last = new
                end))
            end
        end
        local pg = LP:FindFirstChildOfClass("PlayerGui")
        for _, d in ipairs(LP:GetDescendants()) do
            if not (pg and d:IsDescendantOf(pg)) then pcall(maybe_value, d) end
        end
        keep(LP.DescendantAdded:Connect(function(d) pcall(maybe_value, d) end))
    end

    --------------------------------------------------------------------- HUD text (weave stacks / stamina)

    local gui_last = {}
    local function watch_gui(obj)
        if not (obj:IsA("TextLabel") or obj:IsA("TextButton") or obj:IsA("GuiObject")) then return end
        local named = has_word(obj.Name, GUI_WORDS) or (obj.Parent and has_word(obj.Parent.Name, GUI_WORDS))
        if obj:IsA("TextLabel") or obj:IsA("TextButton") then
            keep(obj:GetPropertyChangedSignal("Text"):Connect(function()
                local txt = obj.Text
                if not named and not has_word(txt, GUI_WORDS) then return end
                local t = now()
                if t - (gui_last[obj] or -1) < 0.3 then return end
                gui_last[obj] = t
                local knote, key = key_note()
                emit("gui", { path = obj:GetFullName(), text = string.sub(txt, 1, 80), key = key },
                    string.format("HUD %s = %q%s", obj.Name, string.sub(txt, 1, 80), knote))
            end))
        end
        if named then
            -- bars: log size changes, drops always, refills at most once a second
            local last, last_up = obj.Size.X.Scale, -1
            keep(obj:GetPropertyChangedSignal("Size"):Connect(function()
                local v = obj.Size.X.Scale
                local t = now()
                if v > last and t - last_up < 1 then last = v; return end
                if v > last then last_up = t end
                if math.abs(v - last) < 0.005 then return end
                local knote, key = key_note()
                emit("guibar", { path = obj:GetFullName(), v = r2(v), old = r2(last), key = key },
                    string.format("HUD bar %s %.2f -> %.2f%s", obj.Name, last, v, knote))
                last = v
            end))
            keep(obj:GetPropertyChangedSignal("Visible"):Connect(function()
                local knote, key = key_note()
                emit("guivis", { path = obj:GetFullName(), v = obj.Visible, key = key },
                    string.format("HUD %s visible = %s%s", obj.Name, tostring(obj.Visible), knote))
            end))
        end
    end

    task.spawn(function()
        local pg = LP:WaitForChild("PlayerGui", 10)
        if not pg then return end
        for _, d in ipairs(pg:GetDescendants()) do pcall(watch_gui, d) end
        keep(pg.DescendantAdded:Connect(function(d) pcall(watch_gui, d) end))
    end)

    --------------------------------------------------------------------- remotes

    -- server -> me
    local rin_n = {}
    local function hook_remote_in(re)
        if not (re:IsA("RemoteEvent") or re:IsA("UnreliableRemoteEvent")) then return end
        keep(re.OnClientEvent:Connect(function(...)
            local name = re.Name
            rin[name] = (rin[name] or 0) + 1
            -- TweenEffectEvent = the server telling your client to draw effects (projectiles that
            -- only exist client-side, like the Cambion's homing hellfire). Never muted, logged deep.
            local deep = name == "TweenEffectEvent"
            local never_mute = deep or name == "WeaveBuffEvent"   -- the server's "weave caught it" signal
            if rin[name] > MUTE_AFTER * 5 and not never_mute then
                if rin[name] == MUTE_AFTER * 5 + 1 then emit("muted", { what = "remote in " .. name }, "remote " .. name .. " is noisy, muted") end
                return
            end
            local args
            if deep then
                DEEP = true
                args = repr_args(...)
                DEEP = false
            else
                args = repr_args(...)
            end
            local r = root()
            local src = r and nearest_mob(r.Position)
            local dt, atk = since_attack(src)
            emit("rin", { remote = re:GetFullName(), args = args, atk = atk and atk.id or nil,
                          since = dt and r2(dt) or nil },
                string.format("<- %s(%s)%s", name, args,
                    dt and string.format("  [%.2fs into %s#%d %s]", dt, src.label, src.uid, atk.name) or ""))
        end))
    end
    for _, d in ipairs(ReplicatedStorage:GetDescendants()) do pcall(hook_remote_in, d) end
    keep(ReplicatedStorage.DescendantAdded:Connect(function(d) pcall(hook_remote_in, d) end))

    -- me -> server
    G.VCR_sink = function(remote, method, ...)
        if not SELF.running or not HOOK_REMOTES then return end
        local cls = remote.ClassName
        if cls ~= "RemoteEvent" and cls ~= "UnreliableRemoteEvent" and cls ~= "RemoteFunction" then return end
        local name = remote.Name
        rout[name] = (rout[name] or 0) + 1
        if rout[name] > MUTE_AFTER * 5 then return end
        local args = repr_args(...)
        local knote, key = key_note()
        if key then follow("remote " .. name) end
        emit("rout", { remote = remote:GetFullName(), method = method, args = args, key = key },
            string.format("-> %s:%s(%s)%s", name, method, args, knote))
    end

    if HOOK_REMOTES and hookmetamethod and getnamecallmethod and not G.VCR_hooked then
        G.VCR_hooked = true
        local cc = checkcaller or function() return false end
        local old
        old = hookmetamethod(game, "__namecall", function(self, ...)
            local sink = G.VCR_sink
            if sink and not cc() then
                local m = getnamecallmethod()
                if m == "FireServer" or m == "InvokeServer" then
                    pcall(sink, self, m, ...)
                end
            end
            return old(self, ...)
        end)
    end

    --------------------------------------------------------------------- keys

    keep(UIS.InputBegan:Connect(function(input, gp)
        if not SELF.running or UIS:GetFocusedTextBox() then return end
        local ut = input.UserInputType
        local key
        if ut == Enum.UserInputType.Keyboard then key = input.KeyCode.Name
        elseif ut == Enum.UserInputType.MouseButton1 then key = "M1"
        elseif ut == Enum.UserInputType.MouseButton2 then key = "M2"
        elseif ut == Enum.UserInputType.MouseButton3 then key = "M3"
        else return end

        if key == "End" then SELF.stop("End pressed"); return end
        if key == "Insert" then emit("MARK", {}, "=============== MARK ==============="); return end
        if key == "Delete" then flush(); return end

        local t = now()
        recent_keys[#recent_keys + 1] = { key = key, t = t }
        if #recent_keys > 40 then table.remove(recent_keys, 1) end
        keystats[key] = keystats[key] or { n = 0, follow = {} }
        keystats[key].n += 1

        -- note the press on every attack that is still live, with how far into it you pressed
        local during = {}
        for _, atk in ipairs(live_attacks) do
            local dt = t - atk.t
            if dt <= HIT_WINDOW then
                table.insert(atk.keys, { key, dt })
                if atk.dist <= NEAR then during[#during + 1] = string.format("%.2fs into %s#%d %s", dt, atk.info.label, atk.info.uid, atk.name) end
            end
        end
        emit("key", { key = key, gp = gp, during = during },
            string.format("KEY %s%s%s", key, gp and " (ui)" or "",
                #during > 0 and ("   " .. table.concat(during, " | ")) or ""))
    end))

    keep(UIS.InputEnded:Connect(function(input)
        if input.UserInputType == Enum.UserInputType.Keyboard and SELF.running then
            emit("keyup", { key = input.KeyCode.Name })
        end
    end))

    --------------------------------------------------------------------- finishing attacks

    -- once an attack's window has passed, record whether it landed and what you pressed during it
    local function settle(force)
        local t = now()
        for i = #live_attacks, 1, -1 do
            local atk = live_attacks[i]
            if force or t - atk.t > HIT_WINDOW then
                table.remove(live_attacks, i)
                if atk.hits == 0 and atk.dist <= NEAR then
                    atk.s.clean += 1
                    for _, kp in ipairs(atk.keys) do
                        local k = atk.s.clean_keys[kp[1]]
                        if not k then k = {}; atk.s.clean_keys[kp[1]] = k end
                        table.insert(k, kp[2])
                    end
                end
                local keys = {}
                for _, kp in ipairs(atk.keys) do keys[#keys + 1] = kp[1] .. "@" .. string.format("%.2f", kp[2]) end
                emit("atkend", { mob = atk.info.label, uid = atk.info.uid, id = atk.id, name = atk.name,
                                 dist = r2(atk.dist), hits = atk.hits, dur = atk.dur and r2(atk.dur) or nil,
                                 keys = keys })
            end
        end
    end

    --------------------------------------------------------------------- summary

    local function fmt_list(t)
        if not t or #t == 0 then return "-" end
        local lo, hi = minmax(t)
        return string.format("%.2f/%.2f/%.2f (n%d)", lo, median(t), hi, #t)
    end

    local function top(tbl, n)
        local arr = {}
        for k, v in pairs(tbl) do arr[#arr + 1] = { k, type(v) == "table" and #v or v } end
        table.sort(arr, function(a, b) return a[2] > b[2] end)
        local out = {}
        for i = 1, math.min(n, #arr) do out[i] = arr[i][1] .. " x" .. arr[i][2] end
        return table.concat(out, ", ")
    end

    local function write_summary(reason)
        local out = {}
        local function s(fmt, ...) out[#out + 1] = select("#", ...) > 0 and string.format(fmt, ...) or fmt end
        local ping = median(pings)
        s("Veil combat recorder -- summary (%s)", reason or "running")
        s("session %s   ran %.0fs   events %d (dropped %d)   ping median %s ms",
            SESSION, now(), ev_count, dropped, ping and tostring(math.floor(ping)) or "?")
        s("hits on your summons / other players timed: %d", ohits_total)
        s("hits where a hitbox covering you appeared first: %d of %d   lead %s",
            #box_leads, hits_total + unblamed.n, fmt_list(box_leads))
        s("  -> dodge-on-hitbox works for an attack only if its HITBOX LEAD > ping + dash start-up")
        s("attacks seen %d   hits taken %d   hits with no attack to blame %d (%.0f dmg)",
            attacks_total, hits_total, unblamed.n, unblamed.dmg)
        s("")
        s("== ENEMY ATTACKS  (times are seconds after the attack animation STARTED) ==")
        s("hit delay     = when its damage landed on you  -> dodge must be ACTIVE by then")
        s("on others     = same timing, measured on your summons / other players")
        s("hitbox at     = when a hitbox/effect part appeared")
        s("clean         = came at you (<%d studs) and did NOT hit you; clean keys = what you pressed then", NEAR)
        s("")
        local keys = {}
        for k, st in pairs(stats) do
            if not (st.looped and LOCO[st.prio]) then keys[#keys + 1] = k end
        end
        table.sort(keys, function(a, b)
            local A, B = stats[a], stats[b]
            if A.hits + A.ohits ~= B.hits + B.ohits then return A.hits + A.ohits > B.hits + B.ohits end
            return A.near > B.near
        end)
        for _, k in ipairs(keys) do
            local st = stats[k]
            s("%s  |  %s  |  %s", st.mob, st.name, st.id)
            s("    plays %d (near %d)   hits %d (+%d multi, %d horde-ambiguous)   clean %d   len %.2fs   %s%s   dist %s",
                st.plays, st.near, st.hits, st.extra_hits, st.amb, st.clean, st.len, st.prio, st.looped and " looped" or "",
                fmt_list(st.dists))
            s("    hit delay   %s   dmg %s", fmt_list(st.delays), fmt_list(st.dmg))
            if st.ohits > 0 then s("    on others   %s   (%s)", fmt_list(st.odelays), top(st.ovictims, 3)) end
            if #st.hitbox_at > 0 then s("    hitbox at   %s", fmt_list(st.hitbox_at)) end
            if #st.box_lead > 0 then s("    HITBOX LEAD %s   (%d of %d hits had one)", fmt_list(st.box_lead), #st.box_lead, st.hits) end
            if #st.proj_eta > 0 then s("    projectile lands %s", fmt_list(st.proj_eta)) end
            for kf, t in pairs(st.kf) do s("    keyframe %-16s %s", kf, fmt_list(t)) end
            for snd, t in pairs(st.sounds) do s("    sound %-30s %s", string.sub(snd, 1, 30), fmt_list(t)) end
            for a, t in pairs(st.attrs) do s("    mob attr %-25s %s", string.sub(a, 1, 25), fmt_list(t)) end
            for key, t in pairs(st.clean_keys) do s("    clean + pressed %-8s %s", key, fmt_list(t)) end
            s("")
        end

        local loco = {}
        for _, st in pairs(stats) do
            if st.looped and LOCO[st.prio] then loco[#loco + 1] = string.format("%s %s (%s x%d)", st.mob, st.name, st.prio, st.plays) end
        end
        if #loco > 0 then s("(idle/walk anims ignored: %s)", table.concat(loco, "; ")); s("") end

        s("== YOUR KEYS  (what happened within %.1fs after each press) ==", KEY_WINDOW)
        local kk = {}
        for k in pairs(keystats) do kk[#kk + 1] = k end
        table.sort(kk, function(a, b) return keystats[a].n > keystats[b].n end)
        for _, k in ipairs(kk) do
            s("%-8s x%-4d %s", k, keystats[k].n, top(keystats[k].follow, 10))
        end
        s("")
        s("== YOUR ANIMATIONS ==")
        for id, a in pairs(my_anims) do
            local by = {}
            for key, t in pairs(a.keys) do by[#by + 1] = key .. " " .. fmt_list(t) end
            s("%-24s %s  x%d  len %.2f   after key: %s", string.sub(a.name, 1, 24), id, a.n, a.len,
                #by > 0 and table.concat(by, "; ") or "-")
        end
        s("")
        s("== THINGS ADDED TO YOUR CHARACTER  (i-frame / stun / dash-physics candidates) ==")
        local mk = {}
        for k in pairs(mychild) do mk[#mk + 1] = k end
        table.sort(mk, function(a, b) return mychild[a].n > mychild[b].n end)
        for _, k in ipairs(mk) do
            local mc = mychild[k]
            s("%-40s x%-4d lifetime %s   after keys: %s", string.sub(k, 1, 40), mc.n, fmt_list(mc.lifes), top(mc.keys, 4))
        end
        s("")
        s("== REMOTES ==")
        s("server -> you: %s", top(rin, 25))
        if HOOK_REMOTES then s("you -> server: %s", top(rout, 25)) end
        s("")
        s("full detail: timeline_%s.txt / events_%s.jsonl", SESSION, SESSION)
        if writefile then pcall(writefile, SUMMARY, table.concat(out, "\n")) end
    end

    --------------------------------------------------------------------- loops

    task.spawn(function()
        local last_sum, last_ping = now(), -10
        while SELF.running do
            pcall(scan_mobs)
            settle(false)
            local t = now()
            if t - last_ping >= 5 then
                last_ping = t
                local ok, p = pcall(function() return LP:GetNetworkPing() * 1000 end)
                if ok and p then pings[#pings + 1] = p; emit("ping", { ms = math.floor(p) }) end
            end
            flush()
            if t - last_sum >= SUMMARY_EVERY then last_sum = t; pcall(write_summary, "running") end
            task.wait(FLUSH_EVERY)
        end
    end)

    --------------------------------------------------------------------- HUD

    do
        pcall(function()
            local gui = Instance.new("ScreenGui")
            gui.Name = "VeilCombatRecorder"
            gui.ResetOnSpawn = false
            gui.IgnoreGuiInset = true
            gui.Parent = (gethui and gethui()) or game:GetService("CoreGui")
            SELF.gui = gui

            local box = Instance.new("TextLabel")
            box.Size = UDim2.fromOffset(430, 48)
            box.Position = UDim2.new(0, 12, 1, -60)
            box.BackgroundColor3 = Color3.fromRGB(12, 12, 14)
            box.BackgroundTransparency = 0.3
            box.BorderSizePixel = 0
            box.Font = Enum.Font.Code
            box.TextSize = 12
            box.TextXAlignment = Enum.TextXAlignment.Left
            box.TextYAlignment = Enum.TextYAlignment.Top
            box.TextColor3 = Color3.fromRGB(215, 215, 222)
            box.TextTruncate = Enum.TextTruncate.AtEnd
            box.Parent = gui
            Instance.new("UICorner", box).CornerRadius = UDim.new(0, 6)
            local pad = Instance.new("UIPadding", box)
            pad.PaddingLeft, pad.PaddingTop = UDim.new(0, 6), UDim.new(0, 4)

            task.spawn(function()
                while SELF.running do
                    local n = 0
                    for _ in pairs(mobs) do n += 1 end
                    box.Text = string.format("combat recorder  mobs %d  attacks %d  hits %d   End=stop Ins=mark\n%s",
                        n, attacks_total, hits_total, string.sub(last_line, 1, 90))
                    task.wait(0.25)
                end
            end)
        end)
    end

    --------------------------------------------------------------------- stop

    function SELF.stop(reason)
        if not SELF.running then return end
        settle(true)
        emit("stop", { reason = tostring(reason) }, "stopped (" .. tostring(reason) .. ")")
        flush()
        SELF.running = false
        if G.VCR_sink then G.VCR_sink = nil end
        for _, c in ipairs(conns) do pcall(function() c:Disconnect() end) end
        for _, c in ipairs(char_conns) do pcall(function() c:Disconnect() end) end
        for model in pairs(mobs) do unregister(model) end
        pcall(write_summary, reason)
        if SELF.gui then pcall(function() SELF.gui:Destroy() end) end
        print("[VeilCombat] stopped -- " .. SUMMARY)
    end

    emit("start", { session = SESSION, radius = RADIUS, hook = HOOK_REMOTES, clock = os.clock() },
        string.format("recording  (radius %d, remotes hook %s)  End = stop, Insert = mark", RADIUS, tostring(HOOK_REMOTES)))
    print("[VeilCombat] recording -> workspace/" .. DIR .. "  (End = stop + summary)")
-- ======================================================= end standalone body
end

function Recorder.start()
    local ok, err = pcall(launch)
    if not ok then log.warn("[CombatRecorder] start failed: " .. tostring(err)); return end
    local rec = G().VeilCombatRecorder
    if not rec then return end
    -- End key / another instance taking over stops it from inside: flip the toggle off too
    local inner = rec.stop
    rec.stop = function(reason)
        inner(reason)
        if not stopping then pcall(feature.setEnabled, ID, false) end
    end
    log.info("[CombatRecorder] on")
end

function Recorder.stop()
    local rec = G().VeilCombatRecorder
    if rec and rec.running then
        stopping = true
        pcall(rec.stop, "toggled off")
        stopping = false
    end
end

function Recorder.feature()
    return {
        id          = ID,
        name        = "Combat Recorder",
        description = "Records fights for Auto Weave tuning: mob attack animations, projectiles and hitboxes near you, every hit you take (and which attack did it), plus your own dashes and weaves. Touches nothing -- it only watches and writes to workspace/Veil_Combat. Turn it on before a new mob or boss fight so its moves can be added. While on: End = stop, Insert = drop a MARK line, Delete = flush files.",
        default     = false,
        onToggle    = function(v)
            if v then Recorder.start() else Recorder.stop() end
        end,
    }
end

return Recorder
