#!/usr/bin/env python3
"""Pantheon bundler.

Walks src/*.lua in BUILD_ORDER, wraps each in a _MODULES[name] entry, and
generates dist/main.lua with a tiny require shim. Run from anywhere:

    python tools/build.py
"""
from pathlib import Path
import sys

# Keep in sync with the `files` table in src/loader.lua
BUILD_ORDER = [
    "core/env",
    "core/signal",
    "core/log",
    "core/persist",
    "ui/theme",
    "ui/window",
    "ui/components",
    "ui/notify",
    "games/registry",
    "modules/aim/state",
    "modules/aim/targeting",
    "modules/aim/highlight",
    "modules/aim/shiftlock",
    "modules/aim/lockon_plus",
    "modules/aim/lockon",
    "modules/aim/init",
    "init",
]

HEADER = """-- Pantheon
-- Generated by tools/build.py - do not edit dist/ directly.
-- Source: https://github.com/6014m/Pantheon

local _MODULES, _LOADED = {}, {}

local function require(name)
    if _LOADED[name] ~= nil then return _LOADED[name] end
    local m = _MODULES[name]
    if not m then error("[Pantheon] module not found: " .. tostring(name)) end
    _LOADED[name] = true
    local r = m()
    _LOADED[name] = (r == nil) and true or r
    return _LOADED[name]
end

"""

FOOTER = "\nreturn require(\"init\")\n"


def module_name(rel: str) -> str:
    return rel.replace("/", ".")


def read_module(src_dir: Path, rel: str) -> str:
    path = src_dir / (rel + ".lua")
    if not path.is_file():
        raise FileNotFoundError(f"missing module file: {path}")
    return path.read_text(encoding="utf-8")


def wrap_module(name: str, body: str) -> str:
    return f'_MODULES["{name}"] = function()\n{body.rstrip()}\nend\n\n'


def main() -> int:
    repo = Path(__file__).resolve().parent.parent
    src_dir = repo / "src"
    dist_dir = repo / "dist"
    dist_dir.mkdir(exist_ok=True)
    out_path = dist_dir / "main.lua"

    parts = [HEADER]
    for rel in BUILD_ORDER:
        body = read_module(src_dir, rel)
        parts.append(wrap_module(module_name(rel), body))
    parts.append(FOOTER)

    out_path.write_text("".join(parts), encoding="utf-8", newline="\n")
    size_kb = out_path.stat().st_size / 1024
    print(f"Built {out_path.relative_to(repo)} ({size_kb:.1f} KB, {len(BUILD_ORDER)} modules)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
