#!/usr/bin/env python3
"""Regenerates src/games/veil_recorder.lua from the standalone recorder.

The standalone "[Dev] Veil Combat Recorder.lua" (next to this repo) stays the
source of truth; this wraps its whole body in launch() so Pantheon can start it
from a toggle. Re-run after editing the standalone file, then build.py.
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT.parent / "[Dev] Veil Combat Recorder.lua"
OUT = ROOT / "src" / "games" / "veil_recorder.lua"

HEAD = '''-- The Veil: Combat Recorder (Pantheon toggle for "[Dev] Veil Combat Recorder.lua").
-- GENERATED by tools/sync_recorder.py -- edit the standalone file, then re-run it.
--
-- Passive: watches mob attacks, your hits taken, your dashes/weaves, and writes
-- workspace/Veil_Combat/{summary,timeline,events}_<time>.* -- the same files the
-- standalone script writes, so boss_watch.py / miss_report.py read them unchanged.
-- Keys while on: End = stop, Insert = MARK line, Delete = flush now.

local feature = require("ui.feature")
local log     = require("core.log")

local ID = "veil.combat_recorder"
local Recorder = {}
local stopping = false

local function G() return getgenv and getgenv() or _G end

local function launch()
-- ======================================================= standalone body
'''

TAIL = '''
-- ======================================================= end standalone body
end

function Recorder.start()
    local ok, err = pcall(launch)
    if not ok then log.warn("[CombatRecorder] start failed: " .. tostring(err)); return end
    local rec = G().VeilCombatRecorder
    if not rec then return end
    -- End key / another instance taking over stops it from inside: flip the toggle off too
    local inner = rec.stop
    rec.stop = function(reason)
        inner(reason)
        if not stopping then pcall(feature.setEnabled, ID, false) end
    end
    log.info("[CombatRecorder] on")
end

function Recorder.stop()
    local rec = G().VeilCombatRecorder
    if rec and rec.running then
        stopping = true
        pcall(rec.stop, "toggled off")
        stopping = false
    end
end

function Recorder.feature()
    return {
        id          = ID,
        name        = "Combat Recorder",
        description = "Records fights for Auto Weave tuning: mob attack animations, projectiles and hitboxes near you, every hit you take (and which attack did it), plus your own dashes and weaves. Touches nothing -- it only watches and writes to workspace/Veil_Combat. Turn it on before a new mob or boss fight so its moves can be added. While on: End = stop, Insert = drop a MARK line, Delete = flush files.",
        default     = false,
        onToggle    = function(v)
            if v then Recorder.start() else Recorder.stop() end
        end,
    }
end

return Recorder
'''

body = SRC.read_text(encoding="utf-8")
body = "\n".join("    " + l if l.strip() else "" for l in body.splitlines())
OUT.write_text(HEAD + body + TAIL, encoding="utf-8", newline="\n")
print("wrote", OUT, len(body.splitlines()), "lines of body")
