#!/usr/bin/env python3
"""Builds the Veil Combat Recorder Pantheon ADDON from the standalone recorder.

The standalone "[Dev] Veil Combat Recorder.lua" (next to this repo) stays the
source of truth; this wraps its body in launch() inside an addon that only
activates in The Veil. Output goes next to the standalone file AND into Wave's
workspace/Pantheon/addons/ (where the Addons manager loads it from).
Re-run after editing the standalone file.
"""
from pathlib import Path
import os

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT.parent / "[Dev] Veil Combat Recorder.lua"
OUTS = [
    ROOT.parent / "[Veil] Combat Recorder (addon).lua",
    Path(os.environ["LOCALAPPDATA"]) / "Wave" / "workspace" / "Pantheon" / "addons" / "veil_combat_recorder.lua",
]

HEAD = '''-- [Veil] Combat Recorder  (Pantheon ADDON build)
-- GENERATED by [Uni] Pantheon/tools/sync_recorder.py from "[Dev] Veil Combat Recorder.lua"
-- -- edit that file, then re-run the tool.
--
-- Passive: watches mob attacks, hits you take, your dashes/weaves, and writes
-- workspace/Veil_Combat/{summary,timeline,events}_<time>.* (same files as the
-- standalone script, so boss_watch.py / miss_report.py read them unchanged).
-- Keys while recording: Insert = MARK line, Delete = flush now. (End does NOT stop the addon
-- build -- use its toggle, or unload Pantheon, which stops it.)
--
-- Deploy: place in your executor's  Pantheon/addons/  folder (ships as veil_combat_recorder.lua).

Pantheon.register({
    name        = "Veil Combat Recorder",
    description = "Records The Veil fights for Auto Weave tuning (mob attack anims, projectiles, hits you take, your dashes/weaves). Only shows up in The Veil.",
    scope       = { 7970033072, 125503525638054 },
    setup = function(ctx)
        local ID = "addon.veil_combat_recorder.record"
        local stopping = false
        local function G() return getgenv and getgenv() or _G end

        local function launch()
        G().VCR_ADDON = true   -- tells the body it's the addon build (End doesn't stop it)
-- ======================================================= standalone body
'''

TAIL = '''
-- ======================================================= end standalone body
        end

        local function start()
            local ok, err = pcall(launch)
            if not ok then ctx:notify("start failed: " .. tostring(err), 6); return end
            local rec = G().VeilCombatRecorder
            if not rec then return end
            -- backup for "unexecute Pantheon = recorder stops too" (user 2026-09-29): if the Pantheon
            -- instance that started it is unloaded or replaced, stop even if onUnload never ran
            -- (only when the hub handle is visible from here -- otherwise this would stop it at once)
            local owner = G().Pantheon
            if type(owner) == "table" and type(owner.shutdown) == "function" then
                task.spawn(function()
                    while rec.running do
                        task.wait(1)
                        local cur = G().Pantheon
                        if cur ~= owner or not cur then pcall(rec.stop, "Pantheon unloaded"); break end
                    end
                end)
            end
            -- another instance taking over stops it from inside: flip the toggle off too
            local inner = rec.stop
            rec.stop = function(reason)
                inner(reason)
                if not stopping then pcall(Pantheon.feature.setEnabled, ID, false) end
            end
        end

        local function stop()
            local rec = G().VeilCombatRecorder
            if rec and rec.running then
                stopping = true
                pcall(rec.stop, "toggled off")
                stopping = false
            end
        end

        local m = ctx:menu("Combat Recorder")
        m:feature({
            id          = ID,
            name        = "Record Fights",
            description = "Records fights for Auto Weave tuning: mob attack animations, projectiles and hitboxes near you, every hit you take (and which attack did it), plus your own dashes and weaves. Touches nothing -- it only watches and writes to workspace/Veil_Combat. While on: Insert = drop a MARK line, Delete = flush files. Turn this off (or unload Pantheon) to stop it.",
            default     = false,
            onToggle    = function(v) if v then start() else stop() end end,
        })
        ctx:onUnload(stop)
    end,
})
'''

body = SRC.read_text(encoding="utf-8")
body = "\n".join("            " + l if l.strip() else "" for l in body.splitlines())
for out in OUTS:
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(HEAD + body + TAIL, encoding="utf-8", newline="\n")
    print("wrote", out)
